name: Build and Push Docker Image

on:
  push:
    branches: 
      - main

jobs:
  pushing: 
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello, lets started test"

      - name: Building
        uses: docker/setup-buildx-action@v3
